# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Adritian-Free-Hugo-Theme"
license = "MIT"
licenselink = "https://github.com/zetxek/adritian-free-hugo-theme/blob/main/LICENSE"
description = "Minimalistic and clean theme for Hugo, great for Single Page personal websites"
homepage = "https://github.com/zetxek/adritian-free-hugo-theme"
demosite = "https://zetxek.github.io/adritian-demo/"

tags = ["responsive", "clean", "light", "personal"]

features = [
    "widgets"
]

min_version = "0.123.0"

[author]
name = "Adrián Moreno Peña"
homepage = "https://www.adrianmoreno.info"

# If porting an existing theme
[original]
    author = "Raditian"
    homepage = "https://www.radity.com"
    repo = "https://github.com/radity/raditian-free-hugo-theme"